ss = RelativeTo.World:getOrCreateStateSet()

l1=osg.Light()
l1:setLightNum(1)
ls1=osg.LightSource()
ls1:setLight(l1)
ls1:setLocalStateSetModes(osg.StateAttribute.Values.ON)
ss:setAssociatedModes(l1, osg.StateAttribute.Values.ON)
l1:setAmbient(osg.Vec4(.1,.1,.05,1))
l1:setDiffuse(osg.Vec4(.7,.7,.75,1))
l1:setSpecular(osg.Vec4(.1,.1,.05,1))
l1:setLinearAttenuation(.009)
RelativeTo.Room:addChild(ls1)
l1:setPosition(osg.Vec4(-5,3,-5,1))

RelativeTo.World:addChild(Sphere{radius=.23, position = {-5,3,-5}})

mylight = osg.Light()
mylight:setLightNum(0)
mylight:setAmbient(osg.Vec4(.52, .5, .52, 1))
mylight:setConstantAttenuation(.000001)
mylight:setPosition(osg.Vec4(1.5, 2, 2, 0))
mylightsource = osg.LightSource()
mylightsource:setLight(mylight)
mylightsource:setLocalStateSetModes(osg.StateAttribute.Values.ON)
local ss = RelativeTo.World:getOrCreateStateSet()
ss:setAssociatedModes(mylight, osg.StateAttribute.Values.ON)
RelativeTo.Room:addChild(mylightsource)